/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CompleteProfileRouteImport } from './routes/complete-profile'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAiMatchingRouteImport } from './routes/_authenticated/ai-matching'
import { Route as AuthenticatedClinicalTrialsRouteImport } from './routes/_authenticated/clinical-trials'
import { Route as AuthenticatedComplianceRouteImport } from './routes/_authenticated/compliance'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedExportsRouteImport } from './routes/_authenticated/exports'
import { Route as AuthenticatedMatchingResultsRouteImport } from './routes/_authenticated/matching-results'
import { Route as AuthenticatedMonitoringRouteImport } from './routes/_authenticated/monitoring'
import { Route as AuthenticatedPatientProcessingRouteImport } from './routes/_authenticated/patient-processing'
import { Route as AuthenticatedPatientsRouteImport } from './routes/_authenticated/patients'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedClinicalTrialsTrialIdRouteImport } from './routes/_authenticated/clinical-trials_.$trialId'
import { Route as AuthenticatedPatientsPatientIdRouteImport } from './routes/_authenticated/patients_.$patientId'
import { Route as AuthenticatedTrialCandidatesTrialIdRouteImport } from './routes/_authenticated/trial-candidates.$trialId'
import { Route as AuthenticatedPatientProcessingJobIdReviewRouteImport } from './routes/_authenticated/patient-processing_.$jobId.review'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteProfileRoute = CompleteProfileRouteImport.update({
  id: '/complete-profile',
  path: '/complete-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAiMatchingRoute = AuthenticatedAiMatchingRouteImport.update({
  id: '/ai-matching',
  path: '/ai-matching',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClinicalTrialsRoute =
  AuthenticatedClinicalTrialsRouteImport.update({
    id: '/clinical-trials',
    path: '/clinical-trials',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComplianceRoute = AuthenticatedComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExportsRoute = AuthenticatedExportsRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMatchingResultsRoute =
  AuthenticatedMatchingResultsRouteImport.update({
    id: '/matching-results',
    path: '/matching-results',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMonitoringRoute = AuthenticatedMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPatientProcessingRoute =
  AuthenticatedPatientProcessingRouteImport.update({
    id: '/patient-processing',
    path: '/patient-processing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPatientsRoute = AuthenticatedPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClinicalTrialsTrialIdRoute =
  AuthenticatedClinicalTrialsTrialIdRouteImport.update({
    id: '/clinical-trials_/$trialId',
    path: '/clinical-trials/$trialId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPatientsPatientIdRoute =
  AuthenticatedPatientsPatientIdRouteImport.update({
    id: '/patients_/$patientId',
    path: '/patients/$patientId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTrialCandidatesTrialIdRoute =
  AuthenticatedTrialCandidatesTrialIdRouteImport.update({
    id: '/trial-candidates/$trialId',
    path: '/trial-candidates/$trialId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPatientProcessingJobIdReviewRoute =
  AuthenticatedPatientProcessingJobIdReviewRouteImport.update({
    id: '/patient-processing_/$jobId/review',
    path: '/patient-processing/$jobId/review',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ai-matching': typeof AuthenticatedAiMatchingRoute
  '/clinical-trials': typeof AuthenticatedClinicalTrialsRoute
  '/compliance': typeof AuthenticatedComplianceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/exports': typeof AuthenticatedExportsRoute
  '/matching-results': typeof AuthenticatedMatchingResultsRoute
  '/monitoring': typeof AuthenticatedMonitoringRoute
  '/patient-processing': typeof AuthenticatedPatientProcessingRoute
  '/patients': typeof AuthenticatedPatientsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/clinical-trials/$trialId': typeof AuthenticatedClinicalTrialsTrialIdRoute
  '/patients/$patientId': typeof AuthenticatedPatientsPatientIdRoute
  '/trial-candidates/$trialId': typeof AuthenticatedTrialCandidatesTrialIdRoute
  '/patient-processing/$jobId/review': typeof AuthenticatedPatientProcessingJobIdReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ai-matching': typeof AuthenticatedAiMatchingRoute
  '/clinical-trials': typeof AuthenticatedClinicalTrialsRoute
  '/compliance': typeof AuthenticatedComplianceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/exports': typeof AuthenticatedExportsRoute
  '/matching-results': typeof AuthenticatedMatchingResultsRoute
  '/monitoring': typeof AuthenticatedMonitoringRoute
  '/patient-processing': typeof AuthenticatedPatientProcessingRoute
  '/patients': typeof AuthenticatedPatientsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/clinical-trials/$trialId': typeof AuthenticatedClinicalTrialsTrialIdRoute
  '/patients/$patientId': typeof AuthenticatedPatientsPatientIdRoute
  '/trial-candidates/$trialId': typeof AuthenticatedTrialCandidatesTrialIdRoute
  '/patient-processing/$jobId/review': typeof AuthenticatedPatientProcessingJobIdReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/ai-matching': typeof AuthenticatedAiMatchingRoute
  '/_authenticated/clinical-trials': typeof AuthenticatedClinicalTrialsRoute
  '/_authenticated/compliance': typeof AuthenticatedComplianceRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/exports': typeof AuthenticatedExportsRoute
  '/_authenticated/matching-results': typeof AuthenticatedMatchingResultsRoute
  '/_authenticated/monitoring': typeof AuthenticatedMonitoringRoute
  '/_authenticated/patient-processing': typeof AuthenticatedPatientProcessingRoute
  '/_authenticated/patients': typeof AuthenticatedPatientsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/clinical-trials_/$trialId': typeof AuthenticatedClinicalTrialsTrialIdRoute
  '/_authenticated/patients_/$patientId': typeof AuthenticatedPatientsPatientIdRoute
  '/_authenticated/trial-candidates/$trialId': typeof AuthenticatedTrialCandidatesTrialIdRoute
  '/_authenticated/patient-processing_/$jobId/review': typeof AuthenticatedPatientProcessingJobIdReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/complete-profile'
    | '/reset-password'
    | '/ai-matching'
    | '/clinical-trials'
    | '/compliance'
    | '/dashboard'
    | '/documents'
    | '/exports'
    | '/matching-results'
    | '/monitoring'
    | '/patient-processing'
    | '/patients'
    | '/settings'
    | '/clinical-trials/$trialId'
    | '/patients/$patientId'
    | '/trial-candidates/$trialId'
    | '/patient-processing/$jobId/review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/complete-profile'
    | '/reset-password'
    | '/ai-matching'
    | '/clinical-trials'
    | '/compliance'
    | '/dashboard'
    | '/documents'
    | '/exports'
    | '/matching-results'
    | '/monitoring'
    | '/patient-processing'
    | '/patients'
    | '/settings'
    | '/clinical-trials/$trialId'
    | '/patients/$patientId'
    | '/trial-candidates/$trialId'
    | '/patient-processing/$jobId/review'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/complete-profile'
    | '/reset-password'
    | '/_authenticated/ai-matching'
    | '/_authenticated/clinical-trials'
    | '/_authenticated/compliance'
    | '/_authenticated/dashboard'
    | '/_authenticated/documents'
    | '/_authenticated/exports'
    | '/_authenticated/matching-results'
    | '/_authenticated/monitoring'
    | '/_authenticated/patient-processing'
    | '/_authenticated/patients'
    | '/_authenticated/settings'
    | '/_authenticated/clinical-trials_/$trialId'
    | '/_authenticated/patients_/$patientId'
    | '/_authenticated/trial-candidates/$trialId'
    | '/_authenticated/patient-processing_/$jobId/review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CompleteProfileRoute: typeof CompleteProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete-profile': {
      id: '/complete-profile'
      path: '/complete-profile'
      fullPath: '/complete-profile'
      preLoaderRoute: typeof CompleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ai-matching': {
      id: '/_authenticated/ai-matching'
      path: '/ai-matching'
      fullPath: '/ai-matching'
      preLoaderRoute: typeof AuthenticatedAiMatchingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clinical-trials': {
      id: '/_authenticated/clinical-trials'
      path: '/clinical-trials'
      fullPath: '/clinical-trials'
      preLoaderRoute: typeof AuthenticatedClinicalTrialsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compliance': {
      id: '/_authenticated/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof AuthenticatedComplianceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exports': {
      id: '/_authenticated/exports'
      path: '/exports'
      fullPath: '/exports'
      preLoaderRoute: typeof AuthenticatedExportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/matching-results': {
      id: '/_authenticated/matching-results'
      path: '/matching-results'
      fullPath: '/matching-results'
      preLoaderRoute: typeof AuthenticatedMatchingResultsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/monitoring': {
      id: '/_authenticated/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof AuthenticatedMonitoringRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patient-processing': {
      id: '/_authenticated/patient-processing'
      path: '/patient-processing'
      fullPath: '/patient-processing'
      preLoaderRoute: typeof AuthenticatedPatientProcessingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patients': {
      id: '/_authenticated/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AuthenticatedPatientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clinical-trials_/$trialId': {
      id: '/_authenticated/clinical-trials_/$trialId'
      path: '/clinical-trials/$trialId'
      fullPath: '/clinical-trials/$trialId'
      preLoaderRoute: typeof AuthenticatedClinicalTrialsTrialIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patients_/$patientId': {
      id: '/_authenticated/patients_/$patientId'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trial-candidates/$trialId': {
      id: '/_authenticated/trial-candidates/$trialId'
      path: '/trial-candidates/$trialId'
      fullPath: '/trial-candidates/$trialId'
      preLoaderRoute: typeof AuthenticatedTrialCandidatesTrialIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patient-processing_/$jobId/review': {
      id: '/_authenticated/patient-processing_/$jobId/review'
      path: '/patient-processing/$jobId/review'
      fullPath: '/patient-processing/$jobId/review'
      preLoaderRoute: typeof AuthenticatedPatientProcessingJobIdReviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAiMatchingRoute: typeof AuthenticatedAiMatchingRoute
  AuthenticatedClinicalTrialsRoute: typeof AuthenticatedClinicalTrialsRoute
  AuthenticatedComplianceRoute: typeof AuthenticatedComplianceRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedExportsRoute: typeof AuthenticatedExportsRoute
  AuthenticatedMatchingResultsRoute: typeof AuthenticatedMatchingResultsRoute
  AuthenticatedMonitoringRoute: typeof AuthenticatedMonitoringRoute
  AuthenticatedPatientProcessingRoute: typeof AuthenticatedPatientProcessingRoute
  AuthenticatedPatientsRoute: typeof AuthenticatedPatientsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedClinicalTrialsTrialIdRoute: typeof AuthenticatedClinicalTrialsTrialIdRoute
  AuthenticatedPatientsPatientIdRoute: typeof AuthenticatedPatientsPatientIdRoute
  AuthenticatedTrialCandidatesTrialIdRoute: typeof AuthenticatedTrialCandidatesTrialIdRoute
  AuthenticatedPatientProcessingJobIdReviewRoute: typeof AuthenticatedPatientProcessingJobIdReviewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAiMatchingRoute: AuthenticatedAiMatchingRoute,
  AuthenticatedClinicalTrialsRoute: AuthenticatedClinicalTrialsRoute,
  AuthenticatedComplianceRoute: AuthenticatedComplianceRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedExportsRoute: AuthenticatedExportsRoute,
  AuthenticatedMatchingResultsRoute: AuthenticatedMatchingResultsRoute,
  AuthenticatedMonitoringRoute: AuthenticatedMonitoringRoute,
  AuthenticatedPatientProcessingRoute: AuthenticatedPatientProcessingRoute,
  AuthenticatedPatientsRoute: AuthenticatedPatientsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedClinicalTrialsTrialIdRoute:
    AuthenticatedClinicalTrialsTrialIdRoute,
  AuthenticatedPatientsPatientIdRoute: AuthenticatedPatientsPatientIdRoute,
  AuthenticatedTrialCandidatesTrialIdRoute:
    AuthenticatedTrialCandidatesTrialIdRoute,
  AuthenticatedPatientProcessingJobIdReviewRoute:
    AuthenticatedPatientProcessingJobIdReviewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CompleteProfileRoute: CompleteProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
